apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pxe-bootserver-config-pvc
  namespace: network
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
