apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pxe-bootserver-data-pvc
  namespace: network
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
